name: CI - Build & Code Quality

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  # ========================================
  # Build React Frontend (reactwebappdemo)
  # ========================================
  build-react:
    name: Build React SPA
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 18.x ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: 'APPS/reactwebappdemo/package-lock.json'

      - name: Install dependencies
        working-directory: APPS/reactwebappdemo
        run: npm ci

      - name: Run ESLint
        working-directory: APPS/reactwebappdemo
        run: npm run lint --if-present || echo "ESLint config not found, skipping"

      - name: Run TypeScript compiler check
        working-directory: APPS/reactwebappdemo
        run: npx tsc --noEmit || echo "TypeScript check skipped"

      - name: Run tests
        working-directory: APPS/reactwebappdemo
        run: npm test -- --passWithNoTests --watchAll=false --coverage || true

      - name: Build React app
        working-directory: APPS/reactwebappdemo
        run: npm run build
        env:
          CI: true
          REACT_APP_API_BASE_URL: https://api.example.com

      - name: Upload React build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: APPS/reactwebappdemo/build/
          retention-days: 7

      - name: SonarQube Scan for React (Optional)
        uses: SonarSource/sonarcloud-github-action@master
        if: always()
        with:
          projectBaseDir: APPS/reactwebappdemo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

  # ========================================
  # Build .NET 8 Web API (webapiservicedemo)
  # ========================================
  build-dotnet:
    name: Build .NET 8 Web API
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '8.x' ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
          cache: true
          cache-dependency-path: 'APPS/webapiservicedemo/WebApiDemo.csproj'

      - name: Restore dependencies
        working-directory: APPS/webapiservicedemo
        run: dotnet restore

      - name: Build solution
        working-directory: APPS/webapiservicedemo
        run: dotnet build --configuration Release --no-restore

      - name: Run unit tests
        working-directory: APPS/webapiservicedemo
        run: dotnet test --configuration Release --no-build --verbosity normal --logger "trx;LogFileName=test-results.trx" || true

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: APPS/webapiservicedemo/**/test-results.trx

      - name: Run Code Analysis (StyleCop)
        working-directory: APPS/webapiservicedemo
        run: dotnet build --configuration Release /p:EnforceCodeStyleInBuild=true || echo "StyleCop check completed"
        continue-on-error: true

      - name: Upload .NET build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish
          path: APPS/webapiservicedemo/bin/Release/net8.0/publish/
          retention-days: 7

      - name: SonarQube Scan for .NET (Optional)
        uses: SonarSource/sonarcloud-github-action@master
        if: always()
        with:
          projectBaseDir: APPS/webapiservicedemo
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        continue-on-error: true

  # ========================================
  # Lint and Validate Terraform
  # ========================================
  validate-terraform:
    name: Validate Terraform Configuration
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Terraform Format Check
        working-directory: DEPLOYMENT/GITHUBWORKFLOWS
        run: terraform fmt -check -recursive

      - name: Terraform Validate (Terraform)
        working-directory: DEPLOYMENT/GITHUBWORKFLOWS
        run: terraform validate || echo "Terraform config needs initialization"

      - name: Terraform Security Scan (tfsec)
        run: |
          wget https://github.com/aquasecurity/tfsec/releases/download/v1.28.0/tfsec-linux-amd64
          chmod +x tfsec-linux-amd64
          ./tfsec-linux-amd64 DEPLOYMENT/GITHUBWORKFLOWS/ || true
        continue-on-error: true

  # ========================================
  # Code Quality Summary
  # ========================================
  quality-gate:
    name: Quality Gate Check
    runs-on: ubuntu-latest
    needs: [ build-react, build-dotnet, validate-terraform ]
    if: always()
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check Build Status
        run: |
          if [ "${{ needs.build-react.result }}" != "success" ] || [ "${{ needs.build-dotnet.result }}" != "success" ]; then
            echo "❌ Build failed for React or .NET"
            exit 1
          fi
          echo "✅ All builds passed"

      - name: Summary Report
        run: |
          echo "## Build & Quality Report"
          echo "| Component | Status |"
          echo "|-----------|--------|"
          echo "| React SPA | ${{ needs.build-react.result }} |"
          echo "| .NET API | ${{ needs.build-dotnet.result }} |"
          echo "| Terraform | ${{ needs.validate-terraform.result }} |"
