name: Deploy to Azure

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches: [ main ]
    paths:
      - 'APPS/**'
      - 'DEPLOYMENT/GITHUBWORKFLOWS/terraform/**'

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
  AZURE_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}

jobs:
  # ========================================
  # Build & Publish React Frontend
  # ========================================
  build-publish-react:
    name: Build & Publish React
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'
          cache-dependency-path: 'APPS/reactwebappdemo/package-lock.json'

      - name: Install dependencies
        working-directory: APPS/reactwebappdemo
        run: npm ci

      - name: Build React app
        working-directory: APPS/reactwebappdemo
        run: npm run build
        env:
          CI: true
          REACT_APP_API_BASE_URL: ${{ secrets.REACT_APP_API_BASE_URL }}

      - name: Upload React build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: react-build-prod
          path: APPS/reactwebappdemo/build/

  # ========================================
  # Build & Publish .NET 8 Web API
  # ========================================
  build-publish-dotnet:
    name: Build & Publish .NET API
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'
          cache: true
          cache-dependency-path: 'APPS/webapiservicedemo/WebApiDemo.csproj'

      - name: Restore dependencies
        working-directory: APPS/webapiservicedemo
        run: dotnet restore

      - name: Build solution
        working-directory: APPS/webapiservicedemo
        run: dotnet build --configuration Release --no-restore

      - name: Publish .NET app
        working-directory: APPS/webapiservicedemo
        run: dotnet publish -c Release -o ./publish

      - name: Upload .NET publish artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-publish-prod
          path: APPS/webapiservicedemo/publish/

  # ========================================
  # Deploy Infrastructure with Terraform
  # ========================================
  terraform-deploy:
    name: Deploy Infrastructure with Terraform
    runs-on: ubuntu-latest
    needs: [ build-publish-react, build-publish-dotnet ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.0

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ env.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ env.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ env.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ env.AZURE_TENANT_ID }}"
            }

      - name: Terraform Init
        working-directory: DEPLOYMENT/GITHUBWORKFLOWS/terraform
        run: |
          terraform init \
            -backend-config="resource_group_name=${{ secrets.TF_BACKEND_RG }}" \
            -backend-config="storage_account_name=${{ secrets.TF_BACKEND_SA }}" \
            -backend-config="container_name=${{ secrets.TF_BACKEND_CONTAINER }}" \
            -backend-config="key=${{ secrets.TF_BACKEND_KEY }}"

      - name: Terraform Plan
        working-directory: DEPLOYMENT/GITHUBWORKFLOWS/terraform
        run: |
          terraform plan \
            -var="subscription_id=${{ env.AZURE_SUBSCRIPTION_ID }}" \
            -var="client_id=${{ env.AZURE_CLIENT_ID }}" \
            -var="client_secret=${{ env.AZURE_CLIENT_SECRET }}" \
            -var="tenant_id=${{ env.AZURE_TENANT_ID }}" \
            -out=tfplan

      - name: Terraform Apply
        working-directory: DEPLOYMENT/GITHUBWORKFLOWS/terraform
        run: terraform apply -auto-approve tfplan

      - name: Capture Terraform Outputs
        working-directory: DEPLOYMENT/GITHUBWORKFLOWS/terraform
        run: terraform output -json > outputs.json

      - name: Upload Terraform Outputs
        uses: actions/upload-artifact@v4
        with:
          name: terraform-outputs
          path: DEPLOYMENT/GITHUBWORKFLOWS/terraform/outputs.json

  # ========================================
  # Deploy React to Azure Storage
  # ========================================
  deploy-react-azure:
    name: Deploy React to Azure Storage
    runs-on: ubuntu-latest
    needs: [ build-publish-react, terraform-deploy ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download React build artifacts
        uses: actions/download-artifact@v4
        with:
          name: react-build-prod
          path: ./react-build

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ env.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ env.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ env.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ env.AZURE_TENANT_ID }}"
            }

      - name: Upload to Azure Storage
        run: |
          az storage blob upload-batch \
            --account-name ${{ secrets.AZURE_STORAGE_ACCOUNT }} \
            --destination '$web' \
            --source ./react-build \
            --overwrite

      - name: Purge CDN Cache
        run: |
          az cdn endpoint purge \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --profile-name ${{ secrets.AZURE_CDN_PROFILE }} \
            --name ${{ secrets.AZURE_CDN_ENDPOINT }} \
            --content-paths "/*" || echo "CDN purge skipped"
        continue-on-error: true

  # ========================================
  # Deploy .NET API to Azure App Service
  # ========================================
  deploy-dotnet-azure:
    name: Deploy .NET API to Azure App Service
    runs-on: ubuntu-latest
    needs: [ build-publish-dotnet, terraform-deploy ]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download .NET publish artifacts
        uses: actions/download-artifact@v4
        with:
          name: dotnet-publish-prod
          path: ./dotnet-publish

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: |
            {
              "clientId": "${{ env.AZURE_CLIENT_ID }}",
              "clientSecret": "${{ env.AZURE_CLIENT_SECRET }}",
              "subscriptionId": "${{ env.AZURE_SUBSCRIPTION_ID }}",
              "tenantId": "${{ env.AZURE_TENANT_ID }}"
            }

      - name: Deploy to Azure App Service
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APPSERVICE_NAME }}
          package: ./dotnet-publish

      - name: Validate Deployment
        run: |
          sleep 10
          STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://${{ secrets.AZURE_APPSERVICE_NAME }}.azurewebsites.net/swagger)
          if [ $STATUS -eq 200 ]; then
            echo "✅ App Service is healthy"
          else
            echo "⚠️ App Service returned status: $STATUS"
          fi

  # ========================================
  # Deployment Summary & Notifications
  # ========================================
  deployment-summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [ terraform-deploy, deploy-react-azure, deploy-dotnet-azure ]
    if: always()
    
    steps:
      - name: Download Terraform Outputs
        uses: actions/download-artifact@v4
        with:
          name: terraform-outputs
          path: ./outputs

      - name: Parse and Display Outputs
        run: |
          echo "## 🚀 Deployment Summary"
          echo ""
          echo "### Infrastructure"
          if [ -f ./outputs/outputs.json ]; then
            cat ./outputs/outputs.json | jq .
          fi
          echo ""
          echo "### Deployment Status"
          echo "| Component | Status |"
          echo "|-----------|--------|"
          echo "| React SPA | ${{ needs.deploy-react-azure.result }} |"
          echo "| .NET API | ${{ needs.deploy-dotnet-azure.result }} |"
          echo "| Infrastructure | ${{ needs.terraform-deploy.result }} |"

      - name: Send Slack Notification (Optional)
        uses: slackapi/slack-github-action@v1.24.0
        if: always()
        with:
          webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
          payload: |
            {
              "text": "AppLibraryKit Deployment",
              "blocks": [
                {
                  "type": "header",
                  "text": {
                    "type": "plain_text",
                    "text": "🚀 Deployment Completed"
                  }
                },
                {
                  "type": "section",
                  "fields": [
                    {
                      "type": "mrkdwn",
                      "text": "*React SPA*\n${{ needs.deploy-react-azure.result }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*.NET API*\n${{ needs.deploy-dotnet-azure.result }}"
                    },
                    {
                      "type": "mrkdwn",
                      "text": "*Infrastructure*\n${{ needs.terraform-deploy.result }}"
                    }
                  ]
                }
              ]
            }
        continue-on-error: true